### ISSUE TITLE
Implement as a sqlc WASM plugin using `sqlc-dev/plugin-sdk-go`

### ISSUE THREAD

**Issue by andrewmbenton** [walterwanderley/sqlc-grpc#8]
A suggestion from [this Twitter thread](https://twitter.com/voluntas/status/1720058880502456323) is to implement the project as a sqlc WASM plugin. This would allow users to get the grpc codegen output from this project directly from `sqlc generate`. An example sqlc.yaml config might look like:

```yaml
version: '2'
plugins:
- name: walterwanderley-sqlc-grpc
  wasm:
    url: https://some.cdn/walterwanderley-sqlc-grpc.wasm
    sha256: ""
sql:
- schema: schema.sql
  queries: query.sql
  engine: postgresql
  codegen:
  - plugin: walterwanderley-sqlc-grpc
    out: sqlc
    options:
      module: "my-module"
      tracing: true
      litefs: true
  gen:
    go:
      out: sqlc
      sql_package: pgx/v5
```

Running `sqlc generate` with this config would put both the typical sqlc Go codegen output and the grpc output from this project in the `sqlc` directory.

There's a [sqlc plugin sdk for Go](https://github.com/sqlc-dev/plugin-sdk-go) which should make the implementation a little more straightforward.

The only hiccup I can think of would be that [sqlc's `GenerateRequest` proto message](https://github.com/sqlc-dev/sqlc/blob/main/protos/plugin/codegen.proto) that sqlc hands to a plugin may not have enough information to support the grpc codegen work as you've currently implemented it.
